language: node_js
node_js:
- '7'
cache:
  directories:
    - "node_modules"
install:
- npm install
script:
- npm test
- npm run apidocs
deploy:
- provider: script
  script: npm run apidocs-deploy
  skip_cleanup: true
  on:
    branch: master
- provider: heroku
  api_key:
    secure: Ts2q7Tn6ZhQ0IKolqz65myVThoz4OHtghZa0oaZPQ/HIqbkOdP7dG4GnKio5R8pSGTfUvI+ITsTBjfl6ab/oYO6Arl80AwTIaQaWnS6vIIYAIyuXGXni3mPWU6eGpge7FrimbJ7dMkrtPrM7CR2oow0UkWNPzFwGLK8nsMAKS5Hl1Htg2g3eK4UFxi/+rhWo4c1THE5b6wvz6jYbM/+6zMAYNaESbWtA8LiYfLOmh6fPDpRUr0gVg4KNYQiQn7WRtXWP9uHGXJAhH0TUBgrzVnKL3bg4ayE2VAXaTWumjwLv9K8ezdKoT+BAfm/qfmIDidO4lThWvehpXbnvG6Pm5ZS2HhOABQowaU+mwtm++bKksYT4tcDNK2dvbS/ten1s973gxdufmVNyvGx3inYQQVojV/eFHxrB1Rh+6uUl4OJ6NOUsOWTGjVddhAoU8jHYLywtN+LaBsJS+9wuJVYPFdHtOQxjv3fdQPfOO7sSwqwihizkQT0BpvW9ZXwt3CXxk55MVU8Mu2NYkeEO3oZcSOsYkMPxufk0ENGQWqpQ2sWJOXyYHCQhXpK73DI6dJAu5OY1cctT/HZIo/IJvXjFmpBJeRWYt/pgwDLeeQqyGD4hsX7QrBz4+Bfs81LX+Ageps9mkNAxn+TsZifrz+is/6CSf9UwcnF+Df4pQmI3kdk=
  app: hidden-beach-69726
  on:
    repo: matRR/lunchs-api
