language: node_js

node_js:
  - "7"

install:
    - npm install

script:
    - npm run apidocs

deploy:
    provider: script
    script: npm run apidocs-deploy
    skip_cleanup: true
    on:
        branch: master